image: node:8
stages:
  - test
  - build
  - publish

.test: &test
  stage: test
  script:
   - npm install
   - npm run test

Test Node 8:
  image: node:8
  <<: *test

Test Node 9:
  image: node:9
  <<: *test

Test Node 10:
  image: node:10
  <<: *test

Build:
  stage: build
  # only:
  #   - tags
  before_script:
    - npm i -g firescript
  script:
    - fire build

Publish:
  stage: publish
  only:
    - tags
  script:
    - cd dist/
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
    - npm publish
